// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Ability struct {
	ID   int64
	Name string
}

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied int64
	Tstamp    sql.NullTime
}

type Pokedex struct {
	ID          int64
	PokemonName string
	Experience  int64
	CapturedAt  time.Time
	Height      int64
	Weight      int64
	PokemonID   int64
}

type PokedexAbility struct {
	ID          int64
	AbilitiesID int64
	PokemonID   int64
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}
