// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied int64
	Tstamp    sql.NullTime
}

type Pokedex struct {
	ID          int64
	PokemonName string
	PokemonID   int64
	JsonData    string
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}
