// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pokedex.sql

package database

import (
	"context"
	"time"
)

const createPokedexEntry = `-- name: CreatePokedexEntry :one
INSERT INTO pokedex(pokemon_name, experience, captured_at, height, weight, pokemon_id)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, pokemon_name, experience, captured_at, height, weight, pokemon_id
`

type CreatePokedexEntryParams struct {
	PokemonName string
	Experience  int64
	CapturedAt  time.Time
	Height      int64
	Weight      int64
	PokemonID   int64
}

func (q *Queries) CreatePokedexEntry(ctx context.Context, arg CreatePokedexEntryParams) (Pokedex, error) {
	row := q.db.QueryRowContext(ctx, createPokedexEntry,
		arg.PokemonName,
		arg.Experience,
		arg.CapturedAt,
		arg.Height,
		arg.Weight,
		arg.PokemonID,
	)
	var i Pokedex
	err := row.Scan(
		&i.ID,
		&i.PokemonName,
		&i.Experience,
		&i.CapturedAt,
		&i.Height,
		&i.Weight,
		&i.PokemonID,
	)
	return i, err
}

const getPokedex = `-- name: GetPokedex :many
SELECT id, pokemon_name, experience, captured_at, height, weight, pokemon_id FROM pokedex
`

func (q *Queries) GetPokedex(ctx context.Context) ([]Pokedex, error) {
	rows, err := q.db.QueryContext(ctx, getPokedex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pokedex
	for rows.Next() {
		var i Pokedex
		if err := rows.Scan(
			&i.ID,
			&i.PokemonName,
			&i.Experience,
			&i.CapturedAt,
			&i.Height,
			&i.Weight,
			&i.PokemonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPokemonByName = `-- name: GetPokemonByName :one
SELECT id, pokemon_name, experience, captured_at, height, weight, pokemon_id FROM pokedex
WHERE pokemon_name = ?
`

func (q *Queries) GetPokemonByName(ctx context.Context, pokemonName string) (Pokedex, error) {
	row := q.db.QueryRowContext(ctx, getPokemonByName, pokemonName)
	var i Pokedex
	err := row.Scan(
		&i.ID,
		&i.PokemonName,
		&i.Experience,
		&i.CapturedAt,
		&i.Height,
		&i.Weight,
		&i.PokemonID,
	)
	return i, err
}
